name: "my first workflow"

on:
  workflow_dispatch:
    inputs:
      env: 
        required: true
        type: choice
        options:
          - "prd"
          - "tst"

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: ${{inputs.env}}
    steps:
      - name: greet user
        id: greet
        run: echo "msg='Hello ${{vars.NAME}} User'" >> $GITHUB_OUTPUT

      - name: Access steps context value
        run: echo ${{steps.greet.outputs.msg}}
        
        
